### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by GaryGao717** [89z/googleplay#34] opened 2022-04-08 03:06 UTC
Macbook pro, macOS Monterey Version 12.0.1
go version:  go1.18 darwin/amd64

When run googleplay command 
`% googleplay -a com.google.android.youtube`

return this:
`panic: open /Users/XX/Library/Caches/googleplay/token.json: permission denied`

`goroutine 1 [running]:`
`main.main()`
`	PATH/googleplay-master/cmd/googleplay/main.go:60 +0x6e5`

**Comment by 89z** [comment] 2022-04-08 03:33
Hey, I think its caused by this:

~~~go
err := os.MkdirAll(filepath.Dir(name), os.ModeDir)
if err != nil {
   return err
}
~~~

https://github.com/89z/format/blob/2b1c10a80d02771ef24cabd543881c6d11ffa56b/format.go#L16-L19

on my system, that creates a folder no problem. but I think on macOS and Linux, it creates a folder with bad permission.

**Comment by 89z** [comment] 2022-04-08 03:44
Looks like I should be using `os.ModePerm` instead:

https://godocs.io/os#ModePerm

I will try to do a fix soon.

**Comment by 89z** [comment] 2022-04-08 04:07
This should be fixed now on the master branch. If you still have problems let me know

**Closed by 89z** 2022-04-08 04:07 UTC

**Comment by GaryGao717** [comment] 2022-04-08 04:17
> 

Have cloned the latest master, but still get the same permission denied error

**Comment by 89z** [comment] 2022-04-08 04:18
The original broken folder probably still exists.

You might need to just delete that folder using your own methods. Then run the program again after that
